- name: Install wget
  yum:
    name: wget
    state: present
  become: yes
- name: Install vim
  yum:
    name: vim
    state: present
  become: yes
- name: Install telnet
  yum:
    name: telnet
    state: present
  become: yes
